### ISSUE TITLE
Tagged Functions y args[] o ...args como parámetros

### ISSUE THREAD

**Issue by xingfucoder** [EscuelaIt/Curso-ECMAScript-6#2]
Buenas tardes Dani/Joan, ante todo muy buen curso. Aunque no pude realizarlo en su momento sí estoy intentando realizarlo ahora.

En cuanto al Curso-ECMAScript-6 en su sesión 2 se pasó el tema de las tagged functions y el paso del parámetro args, que no sé si estaré en lo correcto pero podría pasarse como cualquiera de los siguientes tipos:

``` javascript
//usando el parámetro como un array ya que si no descompondría el elemento de tipo string
//en sus caracteres al usar arg[x]
var tagged = function(strings, args[]){}

//o mediante el uso del spread operator
var tagged = function(strings, ...args){}
```

Corregidme si me equivoco, es que al final quedó en la sesión 2 pendiente y en la 3 al menos yo, estoy ahora mismo empezando y al ver el código aquí no lo veo. Sólo veo que se reemplazan por arg1 y arg2 en el código del repositorio.

Gracias de antemano.
Saludos.

**Comment by delacruz-dev** [comment]
Exacto. 

El problema que tuve en la sesión 2 es que intenté explicar tagged functions sin haber explicado rest parameters y en directo no fui capaz de ver lo que pasaba, pero es tal cual lo explicas, ambas posibilidades son correctas :)
